version: "3.8"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXTAUTH_URL=http://localhost:3000
        - NEXTAUTH_SECRET=secret
        - NEXT_PUBLIC_MAPBOX_API_TOKEN=token
        - NEXT_PUBLIC_API_URL=https://api.staging.landgriffon.com
    ports:
      - "3000:3000"
    container_name: landgriffon-client
    command: start:prod
    user: "5000:5000"
    env_file: .env.local