all:
	make blue-water-indicator-coefficients grey-water-indicator-coefficients

blue-water-indicator-coefficients:
	python indicator_coefficient_importer.py data/bwfp_indicator_coefficients.csv UWU_T

grey-water-indicator-coefficients:
	python indicator_coefficient_importer.py data/gwfp_indicator_coefficients.csv WQ
