export const TEAM = [
  {
    name: 'Toby Gardner',
    company: 'SEI - Trase',
    role: 'Advisor',
    group: 'support',
    linkedin: 'https://www.linkedin.com/in/toby-gardner-072b6213/',
  },
  {
    name: 'Shirish Bhattarai',
    company: 'SEI - Trase',
    role: 'Advisor',
    group: 'support',
    linkedin: 'https://www.linkedin.com/in/shirishbt/',
  },
  {
    name: 'Emma Gollub',
    company: 'SEI - Trase',
    role: 'Advisor',
    group: 'support',
    linkedin: 'https://www.linkedin.com/in/emma-gollub-85469017',
  },
  {
    name: 'Elena Palao',
    company: 'Vizzuality',
    role: 'Science',
    group: 'core',
    linkedin: 'https://www.linkedin.com/in/elenapalao/',
  },
  {
    name: 'Francis Gassert',
    company: 'Vizzuality',
    role: 'Science',
    group: 'core',
    linkedin: 'https://www.linkedin.com/in/fgassert/',
  },
  {
    name: 'Iker S. Requerey',
    company: 'Vizzuality',
    role: 'Science',
    group: 'core',
    linkedin: 'https://www.linkedin.com/in/iker-s-requerey-11a2791b0/',
  },
  {
    name: 'Ángel Arcones',
    company: 'Vizzuality',
    role: 'Science',
    group: 'support',
    linkedin: 'http://www.linkedin.com/in/angel-arcones',
  },
  {
    name: 'Michael Harfoot',
    company: 'Vizzuality',
    role: 'Science',
    group: 'core',
    linkedin: 'https://www.linkedin.com/in/michael-harfoot-49060a167/',
  },
  {
    name: 'Biel Stela Ballester',
    company: 'Vizzuality',
    role: 'Science',
    group: 'core',
  },
  {
    name: 'Alicia Arenzana',
    company: 'Vizzuality',
    role: 'Science',
    group: 'support',
    linkedin: 'https://www.linkedin.com/in/alicia-arenzana-gil-de-muro-74673534/',
  },
  {
    name: 'David Inga',
    company: 'Vizzuality',
    role: 'Engineering',
    group: 'core',
    linkedin: 'https://www.linkedin.com/in/davidsingal',
  },
  {
    name: 'Joaquín Triñanes',
    company: 'Vizzuality',
    role: 'Engineering',
    group: 'core',
    linkedin: 'https://www.linkedin.com/in/joaquintrinanes',
  },
  {
    name: 'Simão Rodrigues',
    company: 'Vizzuality',
    role: 'Engineering',
    group: 'support',
  },
  {
    name: 'María Luena',
    company: 'Vizzuality',
    role: 'Engineering',
    group: 'core',
    linkedin: 'https://www.linkedin.com/in/mar%C3%ADaluena/',
  },
  {
    name: 'Alex Larrañaga',
    company: 'Vizzuality',
    role: 'Engineering',
    group: 'core',
    linkedin: 'https://www.linkedin.com/in/alex-larranaga',
  },
  {
    name: 'Yulia Belyakova',
    company: 'Vizzuality',
    role: 'Engineering',
    group: 'core',
    linkedin: 'https://www.linkedin.com/in/yulia-belyakova/',
  },
  {
    name: 'Tiago Garcia',
    company: 'Vizzuality',
    role: 'Engineering',
    group: 'core',
    linkedin: 'https://www.linkedin.com/in/tiago-garcia-644679220/',
  },
  {
    name: 'Andrea Rota',
    company: 'Vizzuality',
    role: 'Engineering',
    group: 'support',
  },
  {
    name: 'Miguel Mendoza',
    company: 'Vizzuality',
    role: 'Engineering',
    group: 'support',
  },
  {
    name: 'Irene Eleta',
    company: 'Vizzuality',
    role: 'Design',
    group: 'support',
    linkedin: 'https://www.linkedin.com/in/ieleta/',
  },
  {
    name: 'Andreia Ribeiro',
    company: 'Vizzuality',
    role: 'Design',
    group: 'support',
    linkedin: 'https://www.linkedin.com/in/andreialribeiro/',
  },
  {
    name: 'Ariadna Martínez',
    company: 'Vizzuality',
    role: 'Design',
    group: 'core',
    linkedin: 'https://www.linkedin.com/in/ariadna-ariza-b3511635/',
  },
  {
    name: 'Irene R Vara',
    company: 'Vizzuality',
    role: 'Design',
    group: 'support',
    linkedin: 'https://www.linkedin.com/in/irene-rodriguez-vara',
  },
  {
    name: 'Martin Dubuisson',
    company: 'Vizzuality',
    role: 'Design',
    group: 'support',
    linkedin: 'https://www.linkedin.com/in/martin-dubuisson-190912b2/',
  },
  {
    name: 'Craig Mills',
    company: 'Vizzuality',
    role: 'Business',
    group: 'core',
    linkedin: 'https://www.linkedin.com/in/craigmmills/',
  },
  {
    name: 'David González',
    company: 'Vizzuality',
    role: 'Business',
    group: 'core',
    linkedin: 'https://www.linkedin.com/in/davidgonzalezcamara',
  },
  {
    name: 'Sergio Estella',
    company: 'Vizzuality',
    role: 'Business',
    group: 'core',
    linkedin: 'https://www.linkedin.com/in/sergio-estella/',
  },
  {
    name: 'María Ricart',
    company: 'Vizzuality',
    role: 'Business',
    group: 'core',
    linkedin: 'https://www.linkedin.com/in/maria-ricart-ballara-34734870/',
  },
  {
    name: 'Ane Lizariturry',
    company: 'Vizzuality',
    role: 'Business',
    group: 'support',
    linkedin: 'http://www.linkedin.com/in/ane-lizariturry-apollonio',
  },
  {
    name: 'Rebecca Mankinen Sousa',
    company: 'Vizzuality',
    role: 'Business',
    group: 'support',
    linkedin: 'https://www.linkedin.com/in/rebecca-mankinen-sousa/',
  },
  {
    name: 'Susana Romao',
    company: 'Vizzuality',
    role: 'Project Management',
    group: 'core',
    linkedin: 'https://www.linkedin.com/in/romaosusana/',
  },
  {
    name: 'Jacinta Hamley',
    company: 'Vizzuality',
    role: 'Communications',
    group: 'core',
    linkedin: 'https://www.linkedin.com/in/jacinta-hamley/',
  },
  {
    name: 'Alexander Wowra',
    company: 'Vizzuality',
    role: 'Communications',
    group: 'support',
    linkedin: 'https://www.linkedin.com/in/alexander-wowra-95186167/',
  },
  {
    name: 'Pablo Urrutia',
    company: 'Vizzuality',
    role: 'Marketing Consultant',
    group: 'support',
    linkedin: 'https://www.linkedin.com/in/pablo-urrutia/',
  },
  {
    name: 'Arjen Vrielink',
    company: 'Satelligence',
    role: 'Science',
    group: 'core',
    linkedin: 'https://www.linkedin.com/in/arjenvrielink/',
  },
  {
    name: 'Luca Foresta',
    company: 'Satelligence',
    role: 'Science',
    group: 'core',
    linkedin: 'https://www.linkedin.com/in/lucaforesta',
  },
  {
    name: 'Nanne Tolsma',
    company: 'Satelligence',
    role: 'Business',
    group: 'core',
    linkedin: 'https://www.linkedin.com/in/nannetolsma/',
  },
  {
    name: 'India Flora Mazzei',
    company: 'Satelligence',
    role: 'Marketing Consultant',
    group: 'support',
    linkedin: 'https://www.linkedin.com/in/indiafloramazzei/',
  },
];

export const ROLE_ORDER = [
  'Advisor',
  'Science',
  'Engineering',
  'Design',
  'Business',
  'Communications',
  'Project Management',
  'Marketing Consultant',
];
