set dotenv-load

data_dir := "data"
resampling_resolution := "0.083333"  # 10km

default: download-deforestation-and-carbon resample_deforestation resample_carbon upload_results

download-deforestation-and-carbon:
    gsutil -m cp \
        "gs://landgriffon-gee-bucket/deforestation/carbon_by_human_lu_2020_1000m.tif" \
        "gs://landgriffon-gee-bucket/deforestation/cropland_deforest_2020_1000m.tif" \
        "gs://landgriffon-gee-bucket/deforestation/cropland_deforest_carbon_2020_1000m.tif" \
        "gs://landgriffon-gee-bucket/deforestation/deforest_by_human_lu_2020_1000m.tif" \
        "gs://landgriffon-gee-bucket/deforestation/non_nat_deforest_2020_1000m.tif" \
        "gs://landgriffon-gee-bucket/deforestation/non_nat_deforest_carbon_2020_1000m.tif" \
        {{data_dir}}

resample_deforestation:
    rio warp \
        {{data_dir}}/deforest_by_human_lu_2020_1000m.tif \
        {{data_dir}}/deforest_by_human_lu_2020_10km.tif \
        --resampling average \
        --res {{resampling_resolution}} \
        --overwrite


resample_carbon:
    rio warp \
        {{data_dir}}/carbon_by_human_lu_2020_1000m.tif \
        {{data_dir}}/carbon_by_human_lu_2020_10km.tif \
        --resampling average \
        --res {{resampling_resolution}} \
        --overwrite

#TODO: Implement upload results
upload_results:
