export const INTERVENTIONS_DATA = [
  {
    createdAt: 'string',
    updatedAt: 'string',
    id: 'intervention1',
    title: 'string',
    description: 'string',
    status: 'string',
    type: 'Switch to a new material',
    startYear: 2025,
    endYear: 2025,
    percentage: 50,
    newIndicatorCoefficients: {},
    scenario: {
      createdAt: 'string',
      updatedAt: 'string',
      id: 'string',
      title: 'string',
      description: 'string',
      status: 'string',
      metadata: {},
      user: {
        email: 'string',
        displayName: {},
        fname: {},
        lname: {},
        avatarDataUrl: 'string',
        isActive: true,
        isDeleted: true,
      },
      userId: 'string',
      updatedBy: {
        email: 'string',
        displayName: {},
        fname: {},
        lname: {},
        avatarDataUrl: 'string',
        isActive: true,
        isDeleted: true,
      },
      updatedById: 'string',
    },
    newMaterial: {
      createdAt: 'string',
      updatedAt: 'string',
      id: 'string',
      parentId: 'string',
      name: 'Soybean Oil (RFA-certified)',
      description: 'string',
      hsCodeId: 'string',
      earthstatId: 'string',
      mapspamId: 'string',
      status: 'string',
      metadata: {},
    },
    newBusinessUnit: {
      id: 'string',
      name: 'pep.a1',
      description: 'string',
      status: 'string',
      metadata: {},
    },
    newT1Supplier: {
      createdAt: 'string',
      updatedAt: 'string',
      id: 'string',
      parentId: 'string',
      name: 'string',
      description: 'string',
      status: 'string',
      metadata: {},
    },
    newProducer: {
      createdAt: 'string',
      updatedAt: 'string',
      id: 'string',
      parentId: 'string',
      name: 'string',
      description: 'string',
      status: 'string',
      metadata: {},
    },
    newGeoRegion: {
      id: 'string',
      name: 'string',
      theGeom: {},
      adminRegions: ['string', 'string'],
      sourcingLocations: ['string', 'string'],
    },
    newLocationType: 'string',
    newLocationCountryInput: 'string',
    newLocationAddressInput: 'string',
    newMaterialTonnageRatio: 0,
    // updatedBy: {
    //   email: string,
    //   displayName: {},
    //   fname: {},
    //   lname: {},
    //   avatarDataUrl: string,
    //   isActive: true,
    //   isDeleted: true
    // },
    // updatedById: string
  },
  {
    createdAt: 'string',
    updatedAt: 'string',
    id: 'intervention2',
    title: 'string',
    description: 'string',
    status: 'string',
    type: 'Source from a new supplier or location',
    startYear: 2025,
    endYear: 2025,
    percentage: 50,
    newIndicatorCoefficients: {},
    scenario: {
      createdAt: 'string',
      updatedAt: 'string',
      id: 'string',
      title: 'string',
      description: 'string',
      status: 'string',
      metadata: {},
      user: {
        email: 'string',
        displayName: {},
        fname: {},
        lname: {},
        avatarDataUrl: 'string',
        isActive: true,
        isDeleted: true,
      },
      userId: 'string',
      updatedBy: {
        email: 'string',
        displayName: {},
        fname: {},
        lname: {},
        avatarDataUrl: 'string',
        isActive: true,
        isDeleted: true,
      },
      updatedById: 'string',
    },
    newMaterial: {
      createdAt: 'string',
      updatedAt: 'string',
      id: 'string',
      parentId: 'string',
      name: 'Cocoa',
      description: 'string',
      hsCodeId: 'string',
      earthstatId: 'string',
      mapspamId: 'string',
      status: 'string',
      metadata: {},
    },
    newBusinessUnit: {
      id: 'string',
      name: 'pep.a1',
      description: 'string',
      status: 'string',
      metadata: {},
    },
    newT1Supplier: {
      createdAt: 'string',
      updatedAt: 'string',
      id: 'string',
      parentId: 'string',
      name: 'string',
      description: 'string',
      status: 'string',
      metadata: {},
    },
    newProducer: {
      createdAt: 'string',
      updatedAt: 'string',
      id: 'string',
      parentId: 'string',
      name: 'string',
      description: 'string',
      status: 'string',
      metadata: {},
    },
    newGeoRegion: {
      id: 'string',
      name: 'string',
      theGeom: {},
      adminRegions: ['string', 'string'],
      sourcingLocations: ['string', 'string'],
    },
    newLocationType: 'string',
    newLocationCountryInput: 'string',
    newLocationAddressInput: 'string',
    newMaterialTonnageRatio: 0,
    // updatedBy: {
    //   email: string,
    //   displayName: {},
    //   fname: {},
    //   lname: {},
    //   avatarDataUrl: string,
    //   isActive: true,
    //   isDeleted: true
    // },
    // updatedById: string
  },
  {
    createdAt: 'string',
    updatedAt: 'string',
    id: 'intervention3',
    title: 'string',
    description: 'string',
    status: 'string',
    type: 'Change production efficiency',
    startYear: 2022,
    endYear: 2022,
    percentage: 0,
    newIndicatorCoefficients: {},
    scenario: {
      createdAt: 'string',
      updatedAt: 'string',
      id: 'string',
      title: 'string',
      description: 'string',
      status: 'string',
      metadata: {},
      user: {
        email: 'string',
        displayName: {},
        fname: {},
        lname: {},
        avatarDataUrl: 'string',
        isActive: true,
        isDeleted: true,
      },
      userId: 'string',
      updatedBy: {
        email: 'string',
        displayName: {},
        fname: {},
        lname: {},
        avatarDataUrl: 'string',
        isActive: true,
        isDeleted: true,
      },
      updatedById: 'string',
    },
    newMaterial: {
      createdAt: 'string',
      updatedAt: 'string',
      id: 'string',
      parentId: 'string',
      name: 'Cocoa',
      description: 'string',
      hsCodeId: 'string',
      earthstatId: 'string',
      mapspamId: 'string',
      status: 'string',
      metadata: {},
    },
    newBusinessUnit: {
      id: 'string',
      name: 'pep.a.1.001',
      description: 'string',
      status: 'string',
      metadata: {},
    },
    newT1Supplier: {
      createdAt: 'string',
      updatedAt: 'string',
      id: 'string',
      parentId: 'string',
      name: 'Rubber',
      description: 'string',
      status: 'string',
      metadata: {},
    },
    newProducer: {
      createdAt: 'string',
      updatedAt: 'string',
      id: 'string',
      parentId: 'string',
      name: 'string',
      description: 'string',
      status: 'string',
      metadata: {},
    },
    newGeoRegion: {
      id: 'string',
      name: 'string',
      theGeom: {},
      adminRegions: ['string', 'string'],
      sourcingLocations: ['string', 'string'],
    },
    newLocationType: 'Namazie International',
    newLocationCountryInput: 'string',
    newLocationAddressInput: 'string',
    newMaterialTonnageRatio: 0,
    // updatedBy: {
    //   email: string,
    //   displayName: {},
    //   fname: {},
    //   lname: {},
    //   avatarDataUrl: string,
    //   isActive: true,
    //   isDeleted: true
    // },
    // updatedById: string
  },
  {
    createdAt: 'string',
    updatedAt: 'string',
    id: 'intervention4',
    title: 'string',
    description: 'string',
    status: 'string',
    type: 'Source from a new supplier or location',
    startYear: 2022,
    endYear: 2022,
    percentage: 50,
    newIndicatorCoefficients: {},
    scenario: {
      createdAt: 'string',
      updatedAt: 'string',
      id: 'string',
      title: 'string',
      description: 'string',
      status: 'string',
      metadata: {},
      user: {
        email: 'string',
        displayName: {},
        fname: {},
        lname: {},
        avatarDataUrl: 'string',
        isActive: true,
        isDeleted: true,
      },
      userId: 'string',
      updatedBy: {
        email: 'string',
        displayName: {},
        fname: {},
        lname: {},
        avatarDataUrl: 'string',
        isActive: true,
        isDeleted: true,
      },
      updatedById: 'string',
    },
    newMaterial: {
      createdAt: 'string',
      updatedAt: 'string',
      id: 'string',
      parentId: 'string',
      name: 'Palm oil',
      description: 'string',
      hsCodeId: 'string',
      earthstatId: 'string',
      mapspamId: 'string',
      status: 'string',
      metadata: {},
    },
    newBusinessUnit: {
      id: 'string',
      name: 'pep.a.1.001',
      description: 'string',
      status: 'string',
      metadata: {},
    },
    newT1Supplier: {
      createdAt: 'string',
      updatedAt: 'string',
      id: 'string',
      parentId: 'string',
      name: 'Rubber',
      description: 'string',
      status: 'string',
      metadata: {},
    },
    newProducer: {
      createdAt: 'string',
      updatedAt: 'string',
      id: 'string',
      parentId: 'string',
      name: 'Soybean Oil (RFA-certified)',
      description: 'string',
      status: 'string',
      metadata: {},
    },
    newGeoRegion: {
      id: 'string',
      name: 'string',
      theGeom: {},
      adminRegions: ['string', 'string'],
      sourcingLocations: ['string', 'string'],
    },
    newLocationType: 'Namazie International',
    newLocationCountryInput: 'string',
    newLocationAddressInput: 'string',
    newMaterialTonnageRatio: 0,
    // updatedBy: {
    //   email: string,
    //   displayName: {},
    //   fname: {},
    //   lname: {},
    //   avatarDataUrl: string,
    //   isActive: true,
    //   isDeleted: true
    // },
    // updatedById: string
  },
];

// const INTERVENTIONS_DATA = [
//   {
//     id: 1,
//     title: 'Replace 50% of Palm Oil with Soybean Oil (RFA-certified) by 2025',
//   },
//   {
//     id: 2,
//     title: 'Change supplier of Rubber for pep.a.1.001 to Namazie International in 2022',
//   },
//   {
//     id: 3,
//     title: 'Change production efficiency of Palm oil for pep.a1 in 2 regions by 2025',
//   },
//   {
//     id: 4,
//     title: 'Change production efficiency of Cocoa for pep.a1 in 2 regions by 2025',
//   },
// ];
