import Head from 'next/head';
import { Suspense } from 'react';
import { Canvas } from '@react-three/fiber';
import { OrbitControls } from '@react-three/drei';

import Cookie from 'components/cookie';
import Logo from 'components/logo';

export default function Home() {
  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>Landgriffon | Cookie ingredient traceability</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="px-4 pt-16 pb-10 space-y-10 text-secondary">
        <div className="space-y-4">
          <Logo className="m-auto fill-secondary" />
          
          <h1 className="text-[42px] leading-[36px] font-display font-extrabold text-center uppercase">
            Where does my <br /> cookie come
            <br /> from?
          </h1>

          <div className="w-full h-[140px]">
            <Canvas
              camera={{
                position: [5, 10, 15],
                fov: 45,
                near: 0.1,
                far: 200,
              }}
              gl={{
                physicallyCorrectLights: true,
              }}
              shadows
            >
              <ambientLight intensity={0.5} />
              <directionalLight
                color="white"
                position={[0, 10, -10]}
                intensity={1}
                castShadow
                shadow-camera-far={17.5}
                shadow-camera-left={-10}
                shadow-camera-right={10}
                shadow-camera-top={3}
                shadow-camera-bottom={-3}
              />
              <Suspense fallback={null}>
                <Cookie />
                <OrbitControls
                  makeDefault
                  maxPolarAngle={Math.PI / 2.5}
                  minDistance={8}
                  maxDistance={15}
                />
              </Suspense>
            </Canvas>
          </div>
        </div>

        <div className="space-y-6">
          <p className="text-sm text-center">Average chocolate cookie ingredients</p>
          <ul className="grid grid-cols-4 gap-2 list-none">
            <li>
              <button type="button" className="ingredient-button">
                Cocoa
              </button>
            </li>
            <li>
              <button type="button" className="ingredient-button">
                Wheat
              </button>
            </li>
            <li>
              <button type="button" className="ingredient-button">
                Palm oil
              </button>
            </li>
            <li>
              <button type="button" className="ingredient-button">
                Butter
              </button>
            </li>
          </ul>
        </div>
      </header>
      <main className="flex-1 px-4 bg-secondary">
        <div className=""></div>
      </main>
      <footer className="px-4 text-center bg-gray-dark text-secondary py-14 space-y-7">
        <p className="text-2xl leading-7 uppercase font-display font-extrabold">
          Turn supply chain
          <br /> knowledge into
          <br /> sustainable action.
        </p>
        <a
          href="https://landgriffon.com"
          title="Landgriffon website"
          className="inline-block px-5 py-3 text-center border border-secondary"
        >
          Go to Landgriffon
        </a>
      </footer>
    </div>
  );
}
