
chunks_paths := `find -type f -name "*.tif"`

vrt_filename := non_natural_forest.vrt
cog_filename := non_natural_forest.vrt

convert-to-cog: vrt-from-chunks
    gdal_translate -of COG -co RESAMPLING=nearest -ot Byte -co NUM_THREADS=ALL_CPUS -co BIGTIFF=YES -co COMPRESS=ZSTD -co PREDICTOR=2 -co LEVEL=1 {{vrt_filename}} {{cog_filename}}

vrt-from-chunks:
    gdalbuildvrt -srcnodata 0 {{vrt_filename}} {{chunks_paths}}


