export const newMaterialScenarioInterventionTable = {
  impactTable: [
    {
      indicatorShortName: null,
      indicatorId: '7fdefaaf-9652-4ed7-8888-a263e7fa1bf7',
      groupBy: 'material',
      rows: [
        {
          name: 'Textile',
          children: [
            {
              name: 'Cotton',
              children: [],
              values: [
                {
                  year: 2020,
                  value: 1200,
                  isProjected: false,
                  interventionValue: 0,
                  absoluteDifference: -1200,
                  percentageDifference: 0,
                },
                {
                  year: 2021,
                  value: 1218,
                  isProjected: true,
                  interventionValue: 0,
                  absoluteDifference: -1218,
                  percentageDifference: 0,
                },
                {
                  year: 2022,
                  value: 1236.27,
                  isProjected: true,
                  interventionValue: 0,
                  absoluteDifference: -1236.27,
                  percentageDifference: 0,
                },
                {
                  year: 2023,
                  value: 1254.81405,
                  isProjected: true,
                  interventionValue: 0,
                  absoluteDifference: -1254.81405,
                  percentageDifference: 0,
                },
              ],
            },
            {
              name: 'Linen',
              children: [],
              values: [
                {
                  year: 2020,
                  value: 0,
                  isProjected: false,
                  interventionValue: 1800,
                  absoluteDifference: 1800,
                  percentageDifference: null,
                },
                {
                  year: 2021,
                  value: 0,
                  isProjected: true,
                  interventionValue: 1827,
                  absoluteDifference: 1827,
                  percentageDifference: null,
                },
                {
                  year: 2022,
                  value: 0,
                  isProjected: true,
                  interventionValue: 1854.405,
                  absoluteDifference: 1854.405,
                  percentageDifference: null,
                },
                {
                  year: 2023,
                  value: 0,
                  isProjected: true,
                  interventionValue: 1882.221075,
                  absoluteDifference: 1882.221075,
                  percentageDifference: null,
                },
              ],
            },
            {
              name: 'Wool',
              children: [],
              values: [
                {
                  year: 2020,
                  value: 1200,
                  isProjected: false,
                  interventionValue: 0,
                  absoluteDifference: -1200,
                  percentageDifference: 0,
                },
                {
                  year: 2021,
                  value: 1218,
                  isProjected: true,
                  interventionValue: 0,
                  absoluteDifference: -1218,
                  percentageDifference: 0,
                },
                {
                  year: 2022,
                  value: 1236.27,
                  isProjected: true,
                  interventionValue: 0,
                  absoluteDifference: -1236.27,
                  percentageDifference: 0,
                },
                {
                  year: 2023,
                  value: 1254.81405,
                  isProjected: true,
                  interventionValue: 0,
                  absoluteDifference: -1254.81405,
                  percentageDifference: 0,
                },
              ],
            },
          ],
          values: [
            {
              year: 2020,
              value: 2400,
              isProjected: false,
              interventionValue: 1800,
              absoluteDifference: -600,
              percentageDifference: 75,
            },
            {
              year: 2021,
              value: 2436,
              isProjected: true,
              interventionValue: 1827,
              absoluteDifference: -609,
              percentageDifference: 75,
            },
            {
              year: 2022,
              value: 2472.54,
              isProjected: true,
              interventionValue: 1854.405,
              absoluteDifference: -618.135,
              percentageDifference: 75,
            },
            {
              year: 2023,
              value: 2509.6281,
              isProjected: true,
              interventionValue: 1882.221075,
              absoluteDifference: -627.407025,
              percentageDifference: 75,
            },
          ],
        },
      ],
      yearSum: [
        {
          year: 2020,
          value: 2400,
          interventionValue: 1800,
        },
        {
          year: 2021,
          value: 2436,
          interventionValue: 1827,
        },
        {
          year: 2022,
          value: 2472.54,
          interventionValue: 1854.405,
        },
        {
          year: 2023,
          value: 2509.6281,
          interventionValue: 1882.221075,
        },
      ],
      metadata: {
        unit: 'm3/year',
      },
    },
  ],
};
