name: coverage
on:
  push:
env:
  CC_TEST_REPORTER_URL: https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  CC_TEST_REPORTER_ID: 29691479b26fbb03a9d926e1d6b0bba99c7eae3bb235e26a8b269219fe3c62fc

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch Code Climate reporter CLI
        run: curl -L $CC_TEST_REPORTER_URL > ${{github.workspace}}/cc-test-reporter
      - name: Grant exec permissions
        run: chmod +x cc-test-reporter

      - name: Wait for Client tests to run
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: coverage
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          checkName: testing-client
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Wait for API tests to run
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: coverage
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          checkName: testing-api
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Download API coverage report
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          workflow: testing-api.yml
          name: api-report
          path: ${{github.workspace}}/api/coverage
          repo: ${{github.repository}}

      - name: Download Client coverage report
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          workflow: testing-client.yml
          name: client-report
          path: ${{github.workspace}}/client/coverage
          repo: ${{github.repository}}

      - name: Download test generated dependencies
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          workflow: testing-client.yml
          name: next-dependency
          path: ${{github.workspace}}/client/.next
          repo: ${{github.repository}}

      - name: Format API Report
        run: ./cc-test-reporter format-coverage -p landgriffon -t lcov -o api-coverage.json api/coverage/lcov.info

      - name: Format Client Report
        run: ./cc-test-reporter format-coverage -t lcov -o client-coverage.json client/coverage/lcov.info

      - name: Merge API and Client coverage reports
        run: ./cc-test-reporter sum-coverage *-coverage.json -p 2 -o total-coverage.json

      - name: Upload merged coverage report to Code Climate
        run: ./cc-test-reporter upload-coverage -i total-coverage.json
