name: Frontend Tests

on:
  push:
    paths:
      - '.github/**'
      - 'client/**'
  workflow_dispatch:

env:
  NODE_ENV: test

defaults:
  run:
    working-directory: client

jobs:
  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-20.04
    container: cypress/browsers:node12.18.3-chrome87-ff82
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.16
        uses: actions/setup-node@v2
        with:
          node-version: '14.16'

      - name: Install dependencies
        run: yarn install

      - name: Run Cypress Tests & Generate report
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          command: yarn cypress:ci
          working-directory: client

      - name: Upload Cypress Test Report
        uses: actions/upload-artifact@v2
        with:
          name: frontend-report.lcov
          path: |-
            ${{github.workspace}}/client/coverage/lcov.info


      - name: Trigger Code Upload
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_GHA_PATH }}
          repository: ${{ github.repository }}
          event-type: trigger-coverage-upload
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'






