name: Publish marketing page
on:
  push:
    paths:
      - 'marketing/**'
    branches: [ main ]
  workflow_dispatch:
defaults:
  run:
    working-directory: marketing
jobs:
  marketing:
    name: Deploy marketing site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Installing dependencies
        run: yarn install

      - name: Building the site
        run: yarn build
        env:
          NEXT_PUBLIC_GOOGLE_ANALYTICS: ${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: marketing/out
