name: Publish Docker images

on:
  push:
    branches:
      - 'main'
      - 'staging'
      - 'test'
    paths:
      - 'api/**'
      - 'client/**'
      - 'data/**'
      - '.github/**'
  workflow_dispatch:

jobs:
  push_api_to_registry:
    name: Push API Docker image to Docker Hub
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Wait for API tests to run
        uses: fountainhead/action-wait-for-check@v1.0.0
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          checkName: API Tests
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Wait for Client tests to run
        uses: fountainhead/action-wait-for-check@v1.0.0
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          checkName: Client Tests
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Extract branch name
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "##[set-output name=branch-upper;]$(echo ${GITHUB_REF#refs/heads/} | tr a-z A-Z )"
        id: extract_branch

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: api
          push: true
          tags: vizzuality/landgriffon-api:${{ steps.extract_branch.outputs.branch }}

  push_client_to_registry:
    name: Push Client Docker image to Docker Hub
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Wait for API tests to run
        uses: fountainhead/action-wait-for-check@v1.0.0
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          checkName: API Tests
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Wait for Client tests to run
        uses: fountainhead/action-wait-for-check@v1.0.0
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          checkName: Client Tests
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Extract branch name
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "##[set-output name=branch-upper;]$(echo ${GITHUB_REF#refs/heads/} | tr a-z A-Z )"
        id: extract_branch

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: client
          push: true
          tags: vizzuality/landgriffon-client:${{ steps.extract_branch.outputs.branch }}
          build-args: |
            "NEXTAUTH_URL=${{ secrets[format('NEXTAUTH_URL_{0}', steps.extract_branch.outputs.branch-upper )] }}"
            "NEXTAUTH_SECRET=${{ secrets[format('NEXTAUTH_SECRET_{0}', steps.extract_branch.outputs.branch-upper )] }}"
            "NEXT_PUBLIC_MAPBOX_API_TOKEN=${{ secrets.NEXT_PUBLIC_MAPBOX_API_TOKEN }}"
            "NEXT_PUBLIC_API_URL=${{ secrets[format('NEXT_PUBLIC_API_URL_{0}', steps.extract_branch.outputs.branch-upper )] }}"

  push_data_import_to_registry:
    name: Push Data Import Docker image to Docker Hub
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Wait for API tests to run
        uses: fountainhead/action-wait-for-check@v1.0.0
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          checkName: API Tests
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Wait for Client tests to run
        uses: fountainhead/action-wait-for-check@v1.0.0
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          checkName: Client Tests
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Extract branch name
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "##[set-output name=branch-upper;]$(echo ${GITHUB_REF#refs/heads/} | tr a-z A-Z )"
        id: extract_branch

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: data
          push: true
          tags: vizzuality/landgriffon-data-import:${{ steps.extract_branch.outputs.branch }}
