name: Client Tests

on:
  push:
    paths:
      - 'client/**'
      - '!client/README.md'
      - '!client/CHANGELOG.md'
      - '.github/workflows/testing-client.yml'

  workflow_dispatch:

env:
  NODE_ENV: production

jobs:
  testing-client:
    name: Running client tests
    runs-on: ubuntu-22.04
    container:
      image: cypress/base:22.14.0
    timeout-minutes: 30
    if: ${{ github.ref_name != 'test' }}
    strategy:
      fail-fast: false
    defaults:
      run:
        working-directory: ${{github.workspace}}/client
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version-file: 'client/.nvmrc'

      - uses: pnpm/action-setup@v4
        with:
          package_json_file: 'client/package.json'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: client
          install: false
          build: pnpm build
          start: pnpm start
          wait-on: http://localhost:3000/auth/signin
          config-file: cypress.config.ts
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.CYPRESS_API_URL }}
          NEXT_TELEMETRY_DISABLED: 1
          NEXTAUTH_URL: http://localhost:3000
          NEXTAUTH_SECRET: nyanpony
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
          CYPRESS_API_URL: ${{ secrets.CYPRESS_API_URL }}
          # pass GitHub token to detect new build vs re-run build
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          DEBUG: "cypress:server:args"
          CYPRESS_INSTALL_BINARY: 0

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: ${{github.workspace}}/client/cypress/screenshots
